### ISSUE TITLE
Initialize with a dynamic configuration.

### ISSUE THREAD

**Issue by benedetto-kotzaneck** [EmbeddedEnterprises/ng6-golden-layout#18]
Currently I'm trying to initialize my app with a configuration I get from a web service.
The problem is, I cannot get it before my root AppModule initializes because I have to declare the config in the Golden Layout import statement.

I tried to lazy load a feature module, which declares the golden layout there, but I don't seem to get it running.

I get the following error in multiple components which try to access the GoldenLayout class:

ERROR in : Can't resolve all parameters for OptionsComponent in someComponent.ts: ([object Object], ?, [object Object]). 

Where ? should be an instance of GoldenLayout.

I'd be very glad if someone got a solution to this.
Thanks in advance.

**Comment by martin31821** [comment]
I'd like to see the new ivy compiler used for this, however, several challenges need to be solved in order to dynamically load components. 
Primarily we need to solve the problem of metadata, since angular heavily uses the metadata to inject dependencies and resolve them. (This is where your error is coming from)

**Comment by martin31821** [comment]
In the new ng8 version, it's possible to change the layout at runtime, so you don't need to specify the layout as dependency anymore, which should solve your problem.

Also, there is the possibility to load feature modules lazily by URL, so I'm closing this as fixed.
