### ISSUE TITLE
Problem with canDeactivate

### ISSUE THREAD

**Issue by Abdullah0991** [EmbeddedEnterprises/ng6-golden-layout#31]
Hi,

Using ngx-golden-layout@0.0.20 with Angular 8.2.2

My component (in-which the g-l component lives) have an 'canDeactivate' guard, to ask the user if he really wants to close the app without save his changes:

```
const rootRouterConfig: Routes = [
{
  path: 'main',
  component: AdminLayoutComponent,
  canActivate: [AuthGuard],
  canDeactivate: [PendingChangesGuard],
},
....
]
```

```
@HostListener('window:beforeunload')
canDeactivate(): Observable<boolean> | boolean {
  return window.confirm('Are you sure you want to exit without save ?');
}
```

The problem is the g-l component is get destroyed immediately when I close or reload the window; it shows `Destroy@root!` in the console, whereas it must get destroyed after I confirm the exit.

Any suggestions will be appreciated.

**Comment by martin31821** [comment]
oops, wrong issue.

**Comment by Abdullah0991** [comment]
Any updates about this @martin31821!

**Comment by martin31821** [comment]
Sorry, no update at this time. I didn't had time to investigate and think about a good api design to implement this. Feel free to prepare a PR.

**Comment by Abdullah0991** [comment]
Hi,
As I see the problem is that you call `ngOnDestroy` in the `beforeunload` event, why ? What's the problem if you put the all the cleanup in the `ngOnDestroy` and so the clean will not executed until the app component get destroyed?

**Comment by martin31821** [comment]
Not handling beforeunload would cause severe usability issues, since you need to close all popout windows which would stay open otherwise. 
Furthermore it's considered bad practice to intercept the beforeunload event by having popup modals, instead build your app to update the state immediately and e.g. utilize localstorage to keep local inputs. 
https://developer.mozilla.org/de/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by Abdullah0991** [comment]
> Furthermore it's considered bad practice to intercept the beforeunload event by having popup modals, instead build your app to update the state immediately and e.g. utilize localstorage to keep local inputs.

Sorry, can't get what you suggest because I don't have enough exp in Angular & TS, If you simplify the idea, maybe I can help. Otherwise I have to wait you fix this problem :).

Thanks

**Comment by martin31821** [comment]
After some reading in the DOM spec, events are called in the order they were registered, so my preferred solution would look like this:
- You register your own beforeunload event **before** bootstrapping the golden layout component (Which should already be the case if your golden-layout component is created within your own component)
- When the beforeunload event fires, set a value __cancelGL to the event object 
- The binding looks at this value to determine whether the unload will actually be performed.

@Abdullah0991 what do you think?

**Comment by Abdullah0991** [comment]
Hi, happy to see you back!

- The first step is already done as you expected.

- Can you provide me with an example code to perform the second step so I can test it and tell you what the results.

Regards

**Comment by martin31821** [comment]
I'm going to implement the check, then you can test it

**Comment by martin31821** [comment]
just came up with an even better solution in the `fix/beforeunload` branch.
Please test it and give feedback.

**Comment by Abdullah0991** [comment]
I tried to build the fix branch (with `ng build`) but it fails and throw an error:

> ERROR in ENOENT: no such file or directory, scandir 'C:/Users/user/Documents/GitHub/ng6-golden-layout/dist/ngx-golden-layout'

**Comment by martin31821** [comment]
Run `ng build ngx-golden-layout` first to build the library,
then you can run `ng build` or `ng serve`

**Comment by Abdullah0991** [comment]
I build `ngx-golden-layout` and tried it in my project but same problem, did I have to make some changes to my project also ?

**Comment by martin31821** [comment]
use the previously built library (e.g. via npm link mechanism) and handle the beforeunload like this:
```
  @HostListener('window:beforeunload', ['$event'])
  public onUnload(ev: BeforeUnloadEvent) {
    ev.preventDefault();
    ev.returnValue = "Are you sure?";
    return "Are you sure?";
  }
```

Expected result:
If you're in the root window and you get the beforeunload event, and you cancel this event, nothing should happen.
If you're in the root window and you get the beforeunload event and you let it pass (i.e. unload the page), then it should close all popout windows and unload correctly.
If you're in a popout window, beforeunload will trigger the unload ignoring all cancelations, since in the `pagehide` event, the reference to the owner window isn't available anymore.

**Comment by Abdullah0991** [comment]
Hello,

I test the fix and it looks like it working well, for popout windows, I don't use them in my project so I don't test them.

Thanks you.
