### ISSUE TITLE
Pause WindowSynchronizerService

### ISSUE THREAD

**Issue by mcdenhoed** [EmbeddedEnterprises/ng6-golden-layout#51]
Hi!

I'm using `ngx-golden-layout` in a project that is **not** using GL's pop-out feature. As such, I don't need synchronization of Angular services between windows. I notice while profiling my app that the service is ticking in the background when the app is idle. Is it possible to configure `ngx-golden-layout` to disable popouts/turn off the sync service?

Thanks for writing these bindings, they're awesome!

**Comment by martin31821** [comment]
Can you elaborate on this a bit? If you don't add the `@MultiWindowService` to your services, then the multiwindow functionality should be completely disabled and not cause any overhead.

**Comment by mcdenhoed** [comment]
Sure!

I have a `<golden-layout-root>` element in an Angular Component. I'm initializing it with the following settings:

```javascript
settings: {
      showPopoutIcon: false,
      showMaximiseIcon: false,
      showCloseIcon: false
    }
```

When I profile in Chrome, I see this timer firing occasionally:

https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/d984d1879ff5179d89095b8c338a756fb06a5315/projects/ngx-golden-layout/src/lib/window-sync.service.ts#L38-L42

It's a very small amount of CPU utilization, but figured it would be nice to turn it off if I didn't need it.

I don't see any references to `MultiWindowService` or `WindowSynchronizationService` in my code; is there something I need to do to opt out of them?

**Comment by martin31821** [comment]
That's not a concern, since these are the times, angular would tick anyway.

https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/d984d1879ff5179d89095b8c338a756fb06a5315/projects/ngx-golden-layout/src/lib/window-sync.service.ts#L33-L42

What I'm doing here is overwriting the `tick` method of the original angular `ApplicationRef` (see: https://angular.io/api/core/ApplicationRef#tick)

I need to do that in **all** windows and whenever **any** of the windows occurs to have a tick, share this tick between **all** windows. This infers calling the original `tick` method (here, this is `__tick`) on all windows in their corresponding zones.

As long as you have a single window, all ticks originate from some interaction on your site (you might want to read a bit on zone.js for this matter).

For more information about performance and alternatives to broadcasting, consider #14.

**Comment by mcdenhoed** [comment]
Ahhh, I understand; that makes sense. Thanks for the explanation!
